version: '3.8'  # Убедитесь, что версия указана

services:
  my-backend:
    build: ./BE
    container_name: my-backend
    ports:
      - "3000:3000"
    networks:
      - mynet

  my-frontend:
    build: ./FE
    container_name: my-frontend
    ports:
      - "4000:80"
    networks:
      - mynet

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
     # - /etc/letsencrypt/live/immo-tonn.de/fullchain.pem:/etc/letsencrypt/live/immo-tonn.de/fullchain.pem
     # - /etc/letsencrypt/live/immo-tonn.de/privkey.pem:/etc/letsencrypt/live/immo-tonn.de/privkey.pem
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
