upstream frontend {
    server my-frontend:80;
}

upstream backend {
    server my-backend:3000;
}

server {
    listen 80;
    server_name localhost immo-ton.de www.immo-ton.de;  # Все поддерживаемые домены

    # Редирект с www на основной домен (опционально)
    if ($host = www.immo-ton.de) {
        return 301 http://immo-ton.de$request_uri;
    }

    # Фронтенд
    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Бэкенд (API)
    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Дополнительные настройки
    client_max_body_size 100M;
    keepalive_timeout 60;
}
