name: Deploy Frontend to Hetzner

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Build frontend
      run: |
        cd frontend
        echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}" >> .env
        echo "VITE_HOST=${{ secrets.VITE_HOST }}" >> .env
        npm install
        npm run build

    - name: Deploy to server
      run: |
        ssh root@${{ secrets.SERVER_HOST }} "mkdir -p /var/www/immo-tonn/frontend"
        scp -r ./frontend/dist/* root@${{ secrets.SERVER_HOST }}:/var/www/immo-tonn/frontend/

    - name: Serve frontend with PM2
      run: |
        ssh root@${{ secrets.SERVER_HOST }} <<'ENDSSH'
        pm2 delete frontend || true
        pm2 serve /var/www/immo-tonn/frontend 3000 --name frontend
        pm2 save
ENDSSH
